# Generated by Django 4.2.24 on 2025-12-04 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bill_limit',
            field=models.IntegerField(default=5, help_text='Maximum number of bills allowed per shop', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
