# Generated by Django 4.2.24 on 2025-12-04 08:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_bill_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='bill_limit',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='current_balance',
        ),
        migrations.AlterField(
            model_name='shop',
            name='initial_deposit',
            field=models.DecimalField(decimal_places=2, help_text='Initial deposit amount (credit given to shop)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
